import { GraphieProvider, useGraphie } from "../lib/graphie-context"
import {
  MovableAsymptote,
  MovableCircle,
  MovableExponential,
  MovableLine,
  MovableLineRay,
  MovableLineSegment,
  MovablePoint,
  MovableParabola,
  MovableSinusoid,
  MovableTangent,
  MovableLogarithmic,
  MovableAbsoluteValue,
} from "../lib/movables"
import {
  Arc,
  Asymptotes,
  Circle,
  Ellipse,
  EndpointCircles,
  Exponential,
  Line,
  Logarithmic,
  Parabola,
  Parametric,
  Path,
  Piecewise,
  Plot,
  Polar,
  Polygon,
  Rect,
  Sinusoid,
} from "../lib/graph-components"
import * as svgMath from "./util/svg-math"
import "./styles.css"

export {
  // graphie components
  GraphieProvider,
  useGraphie,
  // movable components
  MovableAsymptote,
  MovableCircle,
  MovableExponential,
  MovableLine,
  MovableLineRay,
  MovableLineSegment,
  MovablePoint,
  MovableParabola,
  MovableSinusoid,
  MovableTangent,
  MovableLogarithmic,
  MovableAbsoluteValue,
  // static components
  Arc,
  Asymptotes,
  Circle,
  Ellipse,
  EndpointCircles,
  Exponential,
  Line,
  Logarithmic,
  Parabola,
  Parametric,
  Path,
  Piecewise,
  Plot,
  Polar,
  Polygon,
  Rect,
  Sinusoid,
  // util
  svgMath,
}
